# /etc/google-cloud-ops-agent/config.yaml
# https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/configuration?hl=ja#default
# https://github.com/GoogleCloudPlatform/ops-agent/issues/650
logging:
  receivers:
    syslog:
      type: files
      include_paths:
      - /var/log/messages
      - /var/log/syslog
  service:
    pipelines:
      default_pipeline:
        receivers: [syslog]
metrics:
  receivers:
    hostmetrics:
      type: hostmetrics
      collection_interval: 60s
  processors:
    metrics_filter:
      type: exclude_metrics
      metrics_pattern: []
  service:
    pipelines:
      default_pipeline:
        receivers: [hostmetrics]
        processors: [metrics_filter]
